### ISSUE TITLE
Rendering Texture2D as <img>

### ISSUE THREAD

**Issue by philfleck** [Kulestar/powerui#6]
Hi,
I am switching to PowerUI, but i am facing some troubles.

How can i render a Textured2D into `<div>` or `<img>`. I tried the approach described
in the Wiki (btw please add some sort of Menu to the Wiki) but without any luck.

here is some sample code on how i tried:
```cs
            var myElement = GetDocument().getById("idImg");
            if(myElement != null)
            {
                Texture2D tx = new Texture2D(320, 320, TextureFormat.ARGB32, false);
                for(int i = 0; i < 200; i++)
                {
                    tx.SetPixel(i, i, Color.red);
                }
                tx.apply();  //?
                myElement.image=tx;
            }
```

Is there some special call on the PowerUI?
Or do i have to call a Update/refresh/rer-render call on the whole ui?
Whats the supposed method for having a chaning texture rendered within the UI?
My texture is filled elsewhere, i just want to set it once so it can be changed elsewhere.

Thx in advance.

**Comment by LukeBriggs4Roads** [comment]
Setting an image via the `image` property is the same as setting background-image via CSS; most likely you should just need to make sure your element has some width and height in order to see the background on there.

**Comment by philfleck** [comment]
Thanks for the reply. Still no luck so far. When i add the size e.g. matching the Texture2D size i always get a grey box.

```
<img id='idImg' style="width:640px;height:480px;">
```
I also tried it with a texture whitout a CPU representation and with one with a CPU representation. in both cases the texture renders right on a simple cube.

Btw, i am using the main-ui without any canvas or smth.
I am testing on 2018.1.0f2 with your 2.5 upkg

**Comment by philfleck** [comment]
bump

**Comment by philfleck** [comment]
Once i use a `RenderTexture` it does render correnctly in the PowerUi `<img>` tag. This comes a big cost for me, because i have to create an extra copy for every change. (`Texture2D` to `RenderTexture`). I have lots of DirectX code using `Texture2D`. The framerates are between 15 and 30 frames per second. I tried switching from `Textured2d` to `RenderTexture` without luck. 

once i set the `myElem.image = myTexture2D` i just get a grey image, but the size is initialized corretly.

Is there any chance getting this to work with the Texture2D?

Thanks.

**Comment by LukeBriggs4Roads** [comment]
Aha ok, if the Texture2D is originating from the GPU then you could try adding this CSS property to your element:

`on-atlas: 0`

i.e. something like:

```
#idImg{
  on-atlas: 0;
  width: ..
  height: ..
}
```

`<div id="idImg"></div>`

This will make PowerUI use the image as-is instead of attempting to optimise it (which is possibly occurring before the pixels are available to the CPU). Hopefully that catches it :)

**Comment by philfleck** [comment]
Very nice, that does the trick!

Thank you.
