### ISSUE TITLE
Wiki+Docu as Pdf?

### ISSUE THREAD

**Issue by philfleck** [Kulestar/powerui#7]
Can you provide the contents of the wiki as pdf?
this ould be great and help a lot.

thx again
best phil

**Comment by Bablakeluke** [comment]
Hey! It looks like there's per-page PDF plugins for WikiMedia if that's what you're after? If you'd like everything then there's the [list of all pages](https://powerui.kulestar.com/wiki/index.php?title=Special:AllPages) (which had a bit of spam so I've just tidied that out again!) - feel free to crawl/ scrape that - or alternatively I'd be happy to provide a database dump from the wiki if that helps :)

**Comment by philfleck** [comment]
"list of all pages" helps a lot - i looked a coupled of times for it, but i couldnt find it.
Thx.
